#!/usr/bin/expect

set timeout 60

# create self public key
spawn ssh-keygen
expect {
    "Enter file in which to save the key" {
        send "\n"
        exp_continue
    }
    "Enter passphrase (empty for no passphrase):" {
        send "\n"
        exp_continue
    }
    "Enter same passphrase again:" {
        send "\n"
        exp_continue
    }
    "Overwrite (y/n)?" {
        send "y\n"
        exp_continue
    }
}

